export  const SET_USER = 'SET_USER';
export const MSG_SHOW = 'MSG_SHOW'
export const MSG_INIT = 'MSG_INIT'

export const FETCH_CONSUME_SUMMARY_REPORT_REQUEST = 'FETCH_CONSUME_SUMMARY_REPORT_REQUEST'
export const FETCH_CONSUME_SUMMARY_REPORT_SUCCESS = 'FETCH_CONSUME_SUMMARY_REPORT_SUCCESS'
export const FETCH_CONSUME_SUMMARY_REPORT_FAILURE = 'FETCH_CONSUME_SUMMARY_REPORT_FAILURE'