/*
 * @Author: poetryxie 
 * @Date: 2017-12-05 10:30:38 
 * @Last Modified by: mikey.zhaopeng
 * @Last Modified time: 2018-01-06 01:50:27
 */

export const MSG_SHOW = 'MSG_SHOW'
export const MSG_INIT = 'MSG_INIT'

export const FETCH_CONSUME_SUMMARY_REPORT_REQUEST = 'FETCH_CONSUME_SUMMARY_REPORT_REQUEST'
export const FETCH_CONSUME_SUMMARY_REPORT_SUCCESS = 'FETCH_CONSUME_SUMMARY_REPORT_SUCCESS'
export const FETCH_CONSUME_SUMMARY_REPORT_FAILURE = 'FETCH_CONSUME_SUMMARY_REPORT_FAILURE'

export const FETCH_CONSUME_CONSUME_REPORT_REQUEST = 'FETCH_CONSUME_CONSUME_REPORT_REQUEST'
export const FETCH_CONSUME_CONSUME_REPORT_SUCCESS = 'FETCH_CONSUME_CONSUME_REPORT_SUCCESS'
export const FETCH_CONSUME_CONSUME_REPORT_FAILURE = 'FETCH_CONSUME_CONSUME_REPORT_FAILURE'

export const FETCH_ADNETWORK_CONSUME_REPORT_REQUEST = 'FETCH_ADNETWORK_CONSUME_REPORT_REQUEST'
export const FETCH_ADNETWORK_CONSUME_REPORT_SUCCESS = 'FETCH_ADNETWORK_CONSUME_REPORT_SUCCESS'
export const FETCH_ADNETWORK_CONSUME_REPORT_FAILURE = 'FETCH_ADNETWORK_CONSUME_REPORT_FAILURE'

export const FETCH_SEARCH_CONSUMER_REQUEST = 'FETCH_SEARCH_CONSUMER_REQUEST'
export const FETCH_SEARCH_CONSUMER_SUCCESS = 'FETCH_SEARCH_CONSUMER_SUCCESS'
export const FETCH_SEARCH_CONSUMER_FAILURE = 'FETCH_SEARCH_CONSUMER_FAILURE'

export const FETCH_CONSUMERNAME_REQUEST = 'FETCH_CONSUMERNAME_REQUEST'
export const FETCH_CONSUMERNAME_SUCCESS = 'FETCH_CONSUMERNAME_SUCCESS'
export const FETCH_CONSUMERNAME_FAILURE = 'FETCH_CONSUMERNAME_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CHANGE_REPORT_DATE = 'CHANGE_REPORT_DATE'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'

export const LOADING_SEARCH_HISTORY = 'LOADING_SEARCH_HISTORY'

export const UPDATECHARTDATA = 'UPDATECHARTDATA'

export const FETCH_CUSTOMER_DETAIL_TEST_DATA = 'FETCH_CUSTOMER_DETAIL_TEST_DATA'